export const SECURITY_ERROR_CODES = {
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  EMPLOYEE_DISABLED: "EMPLOYEE_DISABLED",
  NO_ACTIVE_EMPLOYEE: "NO_ACTIVE_EMPLOYEE",
  NO_ACTIVE_SHIFT: "NO_ACTIVE_SHIFT",
  INVALID_SESSION: "INVALID_SESSION",
  SESSION_EXPIRED: "SESSION_EXPIRED",
} as const;

export type SecurityErrorCode =
  (typeof SECURITY_ERROR_CODES)[keyof typeof SECURITY_ERROR_CODES]; 