import {
  PERMISSIONS,
  type Permission,
} from "@/types/permissions";
import {
  USER_ROLES,
  type UserRole,
} from "@/types/roles";

export const ROLE_PERMISSIONS = {
  [USER_ROLES.ADMIN]: [
    PERMISSIONS.ADMIN_ACCESS,

    PERMISSIONS.EMPLOYEES_MANAGE,
    PERMISSIONS.PRICING_MANAGE,
    PERMISSIONS.SYSTEM_SETTINGS_MANAGE,
    PERMISSIONS.AUDIT_LOG_READ,

    PERMISSIONS.COUPON_CREDIT,

    PERMISSIONS.CASH_RECONCILE,
    PERMISSIONS.SALES_INVOICE_PRINT,
  ],

  [USER_ROLES.EMPLOYEE]: [
    PERMISSIONS.EMPLOYEE_ACCESS,

    PERMISSIONS.SHIFT_OPERATE,
    PERMISSIONS.CUSTOMER_LOOKUP,
    PERMISSIONS.ORDER_CREATE,

    PERMISSIONS.COUPON_DEBIT,

    PERMISSIONS.CASH_RECONCILE,
    PERMISSIONS.SALES_INVOICE_PRINT,
  ],
} as const satisfies Record<
  UserRole,
  readonly Permission[]
>;